import streamlit as st
import pandas as pd
import plotly.graph_objects as go
from sklearn.metrics import classification_report, accuracy_score, precision_score, recall_score, f1_score
import numpy as np
import os

# --- Data Loading and Preparation (Making app.py self-contained) ---

# Variables to hold metrics and dataframes
backtest_df = None
performance_summary_df = None
feature_importance_df = None
y_test = pd.Series([])
y_pred_balanced = pd.Series([])
accuracy_balanced = 0.0
precision_balanced = 0.0
recall_balanced = 0.0
f1_balanced = 0.0

# Check if running in Colab to determine data source
is_colab = 'COLAB_GPU' in os.environ

if is_colab: # If running in Colab, assume variables are in global scope (for initial write-out)
    # These variables need to be explicitly passed or loaded if app.py runs standalone
    # For this demonstration, we ensure they are saved/recomputed if the app runs standalone.
    pass # Variables are assumed to be generated by previous cells in the Colab notebook
else: # If running standalone, load data from files
    # Ensure these paths are correct when deploying
    try:
        # Load DataFrames
        backtest_df = pd.read_csv('backtest_df.csv', index_col='date', parse_dates=True)
        performance_summary_df = pd.read_csv('performance_summary_df.csv')
        feature_importance_df = pd.read_csv('feature_importance_df.csv')

        # Load y_test and y_pred_balanced for classification report
        y_test = pd.read_csv('y_test.csv', header=None).iloc[:, 0].astype(int)
        y_pred_balanced = pd.read_csv('y_pred_balanced.csv', header=None).iloc[:, 0].astype(int)

        # Recalculate scalar metrics from loaded data for standalone execution
        if not y_test.empty and not y_pred_balanced.empty:
            accuracy_balanced = accuracy_score(y_test, y_pred_balanced)
            precision_balanced = precision_score(y_test, y_pred_balanced)
            recall_balanced = recall_score(y_test, y_pred_balanced)
            f1_balanced = f1_score(y_test, y_pred_balanced)

    except FileNotFoundError:
        st.error("Required data files not found. Please ensure data is generated and saved.")
        st.stop()


# --- Streamlit App Layout ---

st.set_page_config(layout="wide", page_title="AI Trading Agent Dashboard")

st.title("AI Trading Agent Performance Dashboard")

# 3. Display the overall classification metrics (accuracy, precision, recall, F1-score for the balanced model)
st.header("1. Model Classification Performance (Balanced Model)")

st.markdown(f"Accuracy: **{accuracy_balanced:.4f}**")
st.markdown(f"Precision: **{precision_balanced:.4f}**")
st.markdown(f"Recall: **{recall_balanced:.4f}**")
st.markdown(f"F1-score: **{f1_balanced:.4f}**")

st.subheader("Classification Report")
# Only display if y_test and y_pred_balanced are sufficiently populated
if not y_test.empty and not y_pred_balanced.empty:
    st.code(classification_report(y_test, y_pred_balanced, zero_division=0))
else:
    st.info("Classification report not available. Please ensure y_test and y_pred_balanced data files are present.")


# 4. Create a sidebar for user controls
st.sidebar.header("Dashboard Controls")

# Ensure backtest_df is not None before proceeding
if backtest_df is None:
    st.warning("Backtest data not loaded. Cannot display trading strategy performance.")
    st.stop()

# 5. Ticker selection
all_tickers = backtest_df['ticker'].unique().tolist()
default_tickers = all_tickers # Select all by default
selected_tickers = st.sidebar.multiselect(
    "Select Ticker(s)",
    options=all_tickers,
    default=default_tickers
)

# 6. Date range selection
min_date = backtest_df.index.min().date()
max_date = backtest_df.index.max().date()

start_date = st.sidebar.date_input("Start Date", value=min_date)
end_date = st.sidebar.date_input("End Date", value=max_date)

# Filter backtest_df based on selections
filtered_backtest_df = backtest_df[
    (backtest_df['ticker'].isin(selected_tickers)) &
    (backtest_df.index.to_series().dt.date >= start_date) &
    (backtest_df.index.to_series().dt.date <= end_date)
].copy() # Use .copy() to avoid SettingWithCopyWarning

# Filter performance_summary_df based on selected tickers
if performance_summary_df is not None:
    filtered_performance_summary_df = performance_summary_df[
        performance_summary_df['ticker'].isin(selected_tickers)
    ].copy() # Use .copy() to avoid SettingWithCopyWarning
else:
    filtered_performance_summary_df = pd.DataFrame()

# 8. Display overall trading strategy metrics
st.header("2. Overall Trading Strategy Performance")

if not filtered_backtest_df.empty:
    # Calculate aggregate strategy returns for all selected tickers
    # Assuming an equally weighted portfolio for simplicity for overall metrics.

    # Convert strategy_returns and Returns to DataFrame and align indices for aggregation
    # Need to handle potential empty groups after filtering
    temp_strategy_returns_grouped = filtered_backtest_df.groupby(['date', 'ticker'])['strategy_returns'].sum()
    if not temp_strategy_returns_grouped.empty:
        temp_strategy_returns = temp_strategy_returns_grouped.unstack(fill_value=0)
    else:
        temp_strategy_returns = pd.DataFrame()

    temp_market_returns_grouped = filtered_backtest_df.groupby(['date', 'ticker'])['Returns'].sum()
    if not temp_market_returns_grouped.empty:
        temp_market_returns = temp_market_returns_grouped.unstack(fill_value=0)
    else:
        temp_market_returns = pd.DataFrame()

    if not temp_strategy_returns.empty and not temp_market_returns.empty:
        # Average returns across selected tickers for overall portfolio
        overall_strategy_daily_returns = temp_strategy_returns.mean(axis=1)
        overall_market_daily_returns = temp_market_returns.mean(axis=1)

        overall_cumulative_strategy_returns = (1 + overall_strategy_daily_returns).cumprod() - 1
        overall_cumulative_buy_and_hold_returns = (1 + overall_market_daily_returns).cumprod() - 1

        # Get the last value of cumulative returns
        final_overall_strategy_returns = overall_cumulative_strategy_returns.iloc[-1] if not overall_cumulative_strategy_returns.empty else 0
        final_overall_buy_and_hold_returns = overall_cumulative_buy_and_hold_returns.iloc[-1] if not overall_cumulative_buy_and_hold_returns.empty else 0

        # Calculate overall Sharpe Ratio and Max Drawdown from aggregate daily returns
        overall_strategy_sharpe = (overall_strategy_daily_returns.mean() / overall_strategy_daily_returns.std()) * (252**0.5) if overall_strategy_daily_returns.std() != 0 else 0 # Annualize daily sharpe
        overall_market_sharpe = (overall_market_daily_returns.mean() / overall_market_daily_returns.std()) * (252**0.5) if overall_market_daily_returns.std() != 0 else 0 # Annualize daily sharpe

        def calculate_max_drawdown_daily(cumulative_returns_series):
            if cumulative_returns_series.empty: return 0
            equity_curve = (1 + cumulative_returns_series).fillna(1)
            running_max = equity_curve.cummax()
            drawdown = (equity_curve - running_max) / running_max
            return drawdown.min()

        overall_strategy_max_drawdown = calculate_max_drawdown_daily(overall_cumulative_strategy_returns)
        overall_buy_and_hold_max_drawdown = calculate_max_drawdown_daily(overall_cumulative_buy_and_hold_returns)

        col1, col2, col3, col4 = st.columns(4)
        with col1:
            st.metric("Strategy Total Return", f"{final_overall_strategy_returns:.2%}")
        with col2:
            st.metric("Buy-and-Hold Total Return", f"{final_overall_buy_and_hold_returns:.2%}")
        with col3:
            st.metric("Strategy Sharpe Ratio", f"{overall_strategy_sharpe:.2f}")
        with col4:
            st.metric("Strategy Max Drawdown", f"{overall_strategy_max_drawdown:.2%}")
    else:
        st.warning("Insufficient data after filtering to calculate overall performance metrics.")

else:
    st.warning("No data available for the selected tickers and date range.")

# 9. Display ticker-specific performance metrics
st.header("3. Ticker-Specific Performance Metrics")
if not filtered_performance_summary_df.empty:
    st.dataframe(filtered_performance_summary_df.set_index('ticker').style.format(
        {"strategy_sharpe": "{:.2f}", "strategy_max_drawdown": "{:.2%}",
         "buy_and_hold_sharpe": "{:.2f}", "buy_and_hold_max_drawdown": "{:.2%}"}
    ))
else:
    st.info("Select tickers from the sidebar to view their specific performance.")

# 10. Create an interactive line chart for cumulative returns
st.header("4. Cumulative Returns Plot")
if not filtered_backtest_df.empty:
    fig = go.Figure()
    for ticker_symbol in filtered_backtest_df['ticker'].unique():
        ticker_data = filtered_backtest_df[filtered_backtest_df['ticker'] == ticker_symbol]
        # Ensure 'date' is directly used as index for plotting
        ticker_data = ticker_data.sort_index()

        fig.add_trace(go.Scatter(
            x=ticker_data.index,
            y=ticker_data['cumulative_strategy_returns'],
            mode='lines',
            name=f'{ticker_symbol} Strategy Returns'
        ))
        fig.add_trace(go.Scatter(
            x=ticker_data.index,
            y=ticker_data['cumulative_buy_and_hold_returns'],
            mode='lines',
            name=f'{ticker_symbol} Buy-and-Hold Returns',
            line=dict(dash='dash')
        ))

    fig.update_layout(
        title='Cumulative Returns: Trading Strategy vs. Buy-and-Hold',
        xaxis_title='Date',
        yaxis_title='Cumulative Returns',
        hovermode='x unified'
    )
    st.plotly_chart(fig, width='stretch')
else:
    st.info("No data available to plot for the selected tickers and date range.")

# 11. Display feature importance
st.header("5. Feature Importance")
if feature_importance_df is not None and not feature_importance_df.empty:
    # Assuming feature_importance_df is already sorted and ready
    fig_feature_importance = go.Figure(data=[go.Bar(
        x=feature_importance_df['Importance'],
        y=feature_importance_df['Feature'],
        orientation='h'
    )])
    fig_feature_importance.update_layout(
        title='Feature Importances from RandomForestClassifier',
        xaxis_title='Importance',
        yaxis_title='Feature',
        yaxis={'categoryorder':'total ascending'}
    )
    st.plotly_chart(fig_feature_importance, width='stretch')
else:
    st.warning("Feature importance data is not available.")
